trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Checkout@2
  displayName: 'Checkout code'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Utilisez la version Python souhaitée
  displayName: 'Set up Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest  # Remplacez par vos tests Python
  displayName: 'Run tests'

- task: Docker@2
  inputs:
    containerRegistry: 'myDockerHubConnection'  # Remplacez par votre nom de connexion Docker Hub
    repository: 'myusername/my-docker-image'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(Build.BuildId)
  displayName: 'Build and Push Docker image'
